### ISSUE TITLE
Are you accepting contributions?

### ISSUE THREAD

**Issue by tmeneau** [salt-formulas/salt-formula-helm#1]
Thanks for this formula! We actually got pretty far along building our own internal Helm formula before we realized this one existed, and would look forward to deprecating our own formula and contributing some fixes and features here instead. I tried running this locally with our relatively vanilla Kubernetes cluster setup, but needed to tweak the formula a bit to get around some syntax issues. 

I'd be happy to fix those issues and additionally contribute some of the features we'd developed for our own formula if you're open to it. Just so you have an idea of what I'm proposing, here are the specific issues I'd like to create and resolve:

1. **Bug Fix**: add sensible defaults and defensive property checks for pillar data (currently the formula yields Jinja syntax errors if certain expected pillar values aren't present or configured with a specific value)                                         
2. **Bug Fix**: remove the `ensure_{{ namespace }}_namespace` states (I believe tiller creates each release's namespace as necessary)
3. **Bug Fix**: add accurate change management for configured repositories (currently indicates each repository was added for every state run) 
4. **Feature**: include the helm command run by salt for each helm_release.py state in the state's return object (to facilitate debugging chart/helm/cluster issues by the user, including ability to run the helm command directly)        
5. **Feature**: add a module function for packaging charts (including updating dependencies). This is particularly useful for Salt-managed chart repositories (such as for our separate [Chartmuseum](https://github.com/chartmuseum/chartmuseum) formula we're intending to open source soon).
6. **Refactor**: separate out kubectl and tiller configuration/installation into their own `helm.kubectl_installed` and `helm.tiller_installed` SLS files (separation of concerns)
7. **Refactor**: add release values to values files on the target minion (to facilitate debugging chart/helm/cluster issues by the user, including ability to run the helm command directly) 
8. **Documentation**: update the `README` to reflect the new changes applied
9. **Documentation**: add comments to the module functions so that they'll appear in `sys.doc helm` module calls

I'd of course be more than happy to collaborate on the design/necessity/implementation of each item in its respective issue. Is this of interest to you?

**Comment by epcim** [comment]
yes we accept contributions. your PR are warmly welcome.

actually thanks for listing the points. i would add obe more, for apps - values, to configure I would like to reuse metadata model and values we uses for traditional deployment https://github.com/Mirantis/reclass-system-salt-model

**Comment by tmeneau** [comment]
Thanks for the quick reply, that's great! I'll get started on this over the next few days.

At first glance I don't think I'm familiar with how you're using the metadata model in the repository you linked to. I'll be happy to take a look, but it's possible I'll either need some assistance from you on that or that I'm not well suited to tackling it.
